apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-service
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
      - name: world-service-container
        image: shas232/world-service:latest
        ports:
        - containerPort: 3000